version: '3.7'

services:
  web:
    # latest when writing
    image: nginx:1.17.6-alpine
    networks:
      - network-php
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./src
        target: /home/www
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/site.conf
        target: /etc/nginx/conf.d/site.conf
  
  phpfpm:
    image: 'php:7.4.1-fpm'
    networks:
      - network-php
    volumes:
      - type: bind
        source: ./src
        target: /home/www

networks:
  network-php: