version: '3.7'

services:
  web:
    cap_drop:
      - ALL
    # Not available in compose files v3 for docker-compose
    # cpu_shares: 1024
    # latest when writing
    image: nginx:1.17.6-alpine
    networks:
      - network-php
    ports:
      - '80:80'
    # Allow access to port 80 for test purpose # Prefer ports > 1024 otherwise
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    # Assign the_docker_peon unprivileged user
    user: 1003:1003
    volumes:
      - type: bind
        source: ./src
        target: /home/www
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/site.conf
        target: /etc/nginx/conf.d/site.conf
  
  phpfpm:
    # TODO: after custom user is set
    # Not available in compose files v3 for docker-compose
    # cpu_shares: 1024
    image: 'php:7.4.1-fpm'
    networks:
      - network-php
    volumes:
      - type: bind
        source: ./src
        target: /home/www

networks:
  network-php:
    driver: bridge
    labels:
      fr.masamune.client: 'masamune'
      fr.masamune.maintainer: 'masamune.code@gmail.com'
      fr.masamune.project: 'test-curated-composed-project'
      fr.masamune.type: 'test'