version: '3.7'

services:
  web:
    cap_drop:
      - ALL
    # Not available in compose files v3 for docker-compose
    # cpu_shares: 1024
    # latest when writing
    healthcheck:
      test: 'stat /etc/nginx/nginx.conf || exit 1'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    image: nginx:1.17.6-alpine
    labels:
      fr.masamune.client: 'masamune'
      fr.masamune.maintainer: 'masamune.code@gmail.com'
      fr.masamune.project: 'curated composed nginx'
      fr.masamune.type: 'test'
    networks:
      - network-php
    ports:
      - '80:80'
    # Allow access to port 80 for test purpose # Prefer ports > 1024 otherwise
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    # Assign the_docker_peon unprivileged user
    user: 1003:1003
    volumes:
      - type: bind
        source: ./src
        target: /home/www
        read_only: true
      # Override default nginx.conf to allow custom docker user
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/site.conf
        target: /etc/nginx/conf.d/site.conf
        read_only: true
  
  phpfpm:
    # TODO: after custom user is set
    # cap_drop:
    #   - SETPCAP
    #   - MKNOD
    #   - AUDIT_WRITE
    #   - CHOWN
    #   - NET_RAW
    #   - DAC_OVERRIDE
    #   - FOWNER
    #   - FSETID
    #   - KILL
    #   - SETGID
    #   - SETUID
    #   - NET_BIND_SERVICE
    #   - SYS_CHROOT
    #   - SETFCAP
    # Not available in compose files v3 for docker-compose
    # cpu_shares: 1024
    healthcheck:
      test: 'stat /etc/passwd || exit 1'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    image: 'php:7.4.1-fpm'
    labels:
      fr.masamune.client: 'masamune'
      fr.masamune.maintainer: 'masamune.code@gmail.com'
      fr.masamune.project: 'curated composed php fpm'
      fr.masamune.type: 'test'
    networks:
      - network-php
    # Allow access to port 80 for test purpose # Prefer ports > 1024 otherwise
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    # Assign the_docker_peon unprivileged user
    user: 1003:1003
    volumes:
      - type: bind
        source: ./src
        target: /home/www

networks:
  network-php:
    driver: bridge
    labels:
      fr.masamune.client: 'masamune'
      fr.masamune.maintainer: 'masamune.code@gmail.com'
      fr.masamune.project: 'test-curated-composed-project'
      fr.masamune.type: 'test'